language: c
compiler: gcc
 
os: linux
dist: xenial
arch: amd64
addons:
    apt:
        update: true
        packages:
            - gcc
            - libcairo2-dev
            - libpoppler-glib-dev

script:
    - make
    - ./pdf-webslides --version | grep -c pdf-webslides
