language: c
compiler: gcc
 
os: linux
dist: 
    - xenial
    - bionic
    - focal
arch: 
    - amd64
    - arm64
addons:
    apt:
        update: true
        packages:
            - gcc
            - libcairo2-dev
            - libpoppler-glib-dev

script:
    - make
    - ./pdf-webslides --version | grep -c pdf-webslides
