language: c
compiler: gcc
 
jobs:
    include:
        - os: linux
          dist: xenial
          arch: amd64
          addons:
              apt:
                  update: true
                  packages:
                      - gcc
                      - libcairo2-dev
                      - libpoppler-glib-dev

        - os: linux
          dist: xenial
          arch: arm64
          addons:
              apt:
                  update: true
                  packages:
                      - gcc
                      - libcairo2-dev
                      - libpoppler-glib-dev
                    
        - os: linux
          dist: bionic
          arch: amd64
          addons:
              apt:
                  update: true
                  packages:
                      - gcc
                      - libcairo2-dev
                      - libpoppler-glib-dev

        - os: linux
          dist: bionic
          arch: arm64
          addons:
              apt:
                  update: true
                  packages:
                      - gcc
                      - libcairo2-dev
                      - libpoppler-glib-dev

        - os: linux
          dist: focal
          arch: amd64
          addons:
              apt:
                  update: true
                  packages:
                      - gcc
                      - libcairo2-dev
                      - libpoppler-glib-dev

        - os: linux
          dist: focal
          arch: arm64
          addons:
              apt:
                  update: true
                  packages:
                      - gcc
                      - libcairo2-dev
                      - libpoppler-glib-dev
                      
script:
    - make
    - ./pdf-webslides --version | grep -c pdf-webslides
